version = 1

[[annotations]]
path = ["src/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Gergő Pintér"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = ["figures/*", "README.md", "data/**/README.md"]
precedence = "override"
SPDX-FileCopyrightText = "2024 Gergő Pintér"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "data/geojson/*"
precedence = "override"
SPDX-FileCopyrightText = "OpenStreetMap contributors"
SPDX-License-Identifier = "ODbL-1.0"

[[annotations]]
path = "data/helsinki/README.txt"
precedence = "override"
SPDX-FileCopyrightText = "2021 Claudia Bergroth, Olle Järv, Henrikki Tenkanen, Matti Manninen, Tuuli Toivonen"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "output/*"
precedence = "override"
SPDX-FileCopyrightText = "2024 Gergő Pintér"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "data/census/b01_01e.xlsx"
precedence = "override"
SPDX-FileCopyrightText = "Official Statistics of Japan"
SPDX-License-Identifier = "LicenseRef-OSJ"

[[annotations]]
path = ["**/.gitignore", "CITATION.cff", "plotting_config.yaml", "pyproject.toml", "OkabeIto.yaml"]
precedence = "override"
SPDX-FileCopyrightText = "2024 Gergő Pintér"
SPDX-License-Identifier = "0BSD"
